image: docker:stable

stages:
  - build
  - package

variables:
  APP_PORT: 8092
  DOCKER_DRIVER: overlay
  APP_NAME: Transfer Service
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

##Build the project
maven-build:
  image: maven:3-jdk-11
  stage: build
  script: "mvn clean package -DskipTests"
  artifacts:
    paths:
      - target/*.jar

#Run Docker build and push it to the Gitlab Registry
docker-build:
  image: docker:19.03.12
  stage: package
  services:
    - docker:19.03.12-dind
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker build -t $IMAGE_TAG .
  - docker push $IMAGE_TAG
